Repository ucsb-cs156-f24/proj-dining-f24-15, pull requests merged in 2024-11, with the labels that each got.

#38 Dining Commons API Backend
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBAPIDiningCommonsController.java
  src/main/java/edu/ucsb/cs156/dining/entities/UCSBAPIDiningCommons.java
  src/main/java/edu/ucsb/cs156/dining/services/UCSBAPIDiningCommonsService.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/dining/controllers/UCSBAPIDiningCommonsControllerTest.java
  src/test/java/edu/ucsb/cs156/dining/services/UCSBAPIDiningCommonsServiceTest.java
Labels: 10

#39 Updated Database table for DiningCommonsReview
  src/main/java/edu/ucsb/cs156/dining/entities/DiningCommonsReview.java
  src/main/java/edu/ucsb/cs156/dining/repositories/DiningCommonsReviewRepository.java
  src/main/resources/db/migration/changes/DiningCommonsReview.json
Labels: 5

#42 Added Menu Items placeholder page
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/MenuItem/MenuItemPage.js
  frontend/src/tests/pages/MenuItem/MenuItemPage.test.js
Labels: 5, Merge Candidate-CI

#47 Created database table for MenuItem and MenuItemReview
  src/main/java/edu/ucsb/cs156/dining/entities/MenuItem.java
  src/main/java/edu/ucsb/cs156/dining/entities/MenuItemReview.java
  src/main/java/edu/ucsb/cs156/dining/repositories/DiningCommonsReviewRepository.java
  src/main/java/edu/ucsb/cs156/dining/repositories/MenuItemRepository.java
  src/main/java/edu/ucsb/cs156/dining/repositories/MenuItemReviewRepository.java
  src/main/resources/db/migration/changes/MenuItem.json
  src/main/resources/db/migration/changes/MenuItemReview.json
Labels: 10

#49 Added placeholder page for individual dining commons
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/DiningCommons/DiningCommonsPage.js
  frontend/src/tests/pages/DiningCommons/DiningCommonsPage.test.js
Labels: 5

#40 Added Table for Meals, incl. fixtures, tests, and stories
  frontend/src/fixtures/mealFixtures.js
  frontend/src/main/components/Meals/MealsTable.js
  frontend/src/stories/components/Meals/MealsTable.stories.js
  frontend/src/tests/components/Meals/MealsTable.test.js
Labels: 10

#45 Added endpoint for meals (updated with description)
  .env.SAMPLE
  src/main/java/edu/ucsb/cs156/dining/controllers/MealController.java
  src/main/java/edu/ucsb/cs156/dining/models/Meal.java
  src/main/java/edu/ucsb/cs156/dining/services/MealService.java
  src/test/java/edu/ucsb/cs156/dining/controllers/MealControllerTest.java
  src/test/java/edu/ucsb/cs156/dining/services/MealServiceTest.java
Labels: 10, Merge Candidate-CI

#52 Added Table for Menu Items, incl. fixtures, tests, and stories
  frontend/src/fixtures/menuItemFixtures.js
  frontend/src/main/components/MenuItems/MenuItemsTable.js
  frontend/src/stories/components/MenuItems/MenuItemsTable.stories.js
  frontend/src/tests/components/MenuItems/MenuItemsTable.test.js
Labels: Ready-For-Staff

#53 Add endpoints for menu item
  src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemController.java
  src/main/java/edu/ucsb/cs156/dining/dto/MenuItemDTO.java
  src/main/java/edu/ucsb/cs156/dining/repositories/MenuItemRepository.java
  src/main/java/edu/ucsb/cs156/dining/services/MenuItemService.java
  src/main/resources/db/migration/changes/MenuItem.json
  src/test/java/edu/ucsb/cs156/dining/controllers/MenuItemControllerTest.java
  src/test/java/edu/ucsb/cs156/dining/services/MealServiceTest.java
  src/test/java/edu/ucsb/cs156/dining/services/MenuItemServiceTest.java
Labels: 10, Merge Candidate-CI

#50 MenuItemReview post (all users)
  src/main/java/edu/ucsb/cs156/dining/ExampleApplication.java
  src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewController.java
  src/main/java/edu/ucsb/cs156/dining/entities/MenuItemReview.java
  src/main/java/edu/ucsb/cs156/dining/repositories/MenuItemReviewRepository.java
  src/main/resources/db/migration/changes/MenuItemReview.json
  src/test/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewControllerTests.java
Labels: 10, Merge Candidate-CI, Ready-For-Staff

#56 Added MyReviews placeholder page and tests, adjusted App.js, AppNavbar.js
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/MyReviews/MyReviewsPage.js
  frontend/src/tests/pages/MyReviews/MyReviewsPage.test.js
Labels: 5, Merge Candidate-CI
